package merkle

// DO NOT EDIT THIS FILE!! this is code generated by enumerator

import "fmt"

// EventOp is the type of merkle event
type EventOp int

// define the various symbolic constants for type EventOp
const (
	MerkleNew    EventOp = 0
	MerkleChange EventOp = 1
	MerkleDelete EventOp = 2
	MerkleDone   EventOp = 3
	MerkleExit   EventOp = 4
)

// String converts EventOp values into strings.
func (x EventOp) String() string {
	switch x {
	case MerkleChange:
		return "MerkleChange"
	case MerkleDelete:
		return "MerkleDelete"
	case MerkleDone:
		return "MerkleDone"
	case MerkleExit:
		return "MerkleExit"
	case MerkleNew:
		return "MerkleNew"
	}
	return fmt.Sprintf("unknown_EventOp_%d", x)
}
