package gorp

// DO NOT EDIT THIS FILE!! this is code generated by enumerator

import "fmt"

type FSRcmd int

const (
	FSRbarf   FSRcmd = 0 // lord help us
	FSRsecond FSRcmd = 1
	FSRthird  FSRcmd = 2 // comment3
)

func String(x FSRcmd) string {
	switch x {
	case FSRthird:
		return "FSRthird"
	case FSRbarf:
		return "FSRbarf"
	case FSRsecond:
		return "FSRsecond"
	}
	return fmt.Sprintf("unknown_FSRcmd_%d", x)
}

// Poot is a glorious type!
type Poot int

const (
	Gamma Poot = 0
	Beta  Poot = 1
)

func String(x Poot) string {
	switch x {
	case Beta:
		return "Beta"
	case Gamma:
		return "Gamma"
	}
	return fmt.Sprintf("unknown_Poot_%d", x)
}
