#!/usr/bin/env python3

from Casbah import Casbah

def main():
	c = Casbah()

	c.exch(None, 'ssh 10.2.10.10 cloud-user')
	c.exch("cloud-user@10.2.10.10's password: ", c.pwd('cloud-user'))

	prompt = r'\[cloud-user@staging01-vnflaf-services-0 ~\]\$ '
	c.exch(prompt, 'date')
	c.exch(prompt, 'ssh -i ./staging01_cu_key.pem staging01-esmon-0')

	prompt = r'\[cloud-user@staging01-esmon-0 ~\]\$ '
	c.exch(prompt, 'ls -ld /var/ericsson/ddc_data')
	c.exch(prompt, None, verbose=True)

	c.interact()


if __name__ == '__main__':
	main()
