#!/usr/bin/env python3

from Casbah import Casbah

def main():
	c = Casbah()

	c.exch(None, 'ssh 10.2.10.10 cloud-user')
	c.exch("cloud-user@10.2.10.10's password: ", c.pwd('cloud-user'))

	prompt = '(\033\\][^\007]*\007)?'
	prompt += r'\[cloud-user@staging01-vnflaf-services-0 ~\]\$ '
	c.exch(prompt, 'stty -echo')
	c.exch(prompt, 'curl http://127.0.0.1:8500/v1/agent/members')
	c.exch(prompt, None)

	with open('members.json', 'wb') as fp:
		fp.write(c.before)
	#with open('members.json-post', 'wb') as fp:
	#	fp.write(c.after)

	c.exch(None, 'exit') # to cas
	c.exch(' > ', 'exit') # to ecgw
	c.exch(' > ', 'exit') # home
	c.close()

if __name__ == '__main__':
	main()
