#!/bin/sh

GOPATH=/home/tom/erixzone

PROMCMD=$GOPATH/bin/prometheus
WEBADDR='localhost:9090'

PDIR=$GOPATH/src/github.com/erixzone/crux/tests/integration/fulcrum2

CERTFLAGS=""
if [ -f $PDIR/prometheus-host.crt ]
then
	CERTFLAGS="--web.server.certificate $PDIR/prometheus-host.crt
		   --web.server.key $PDIR/prometheus-host.key"
fi

case "${1:-start}" in
start)
	exec $PROMCMD --config.file consul.yaml $CERTFLAGS \
		--web.listen-address "$WEBADDR" \
		--web.page-title 'Prometheus - Friend or ENM?' \
		--web.console.templates ./dashboards \
		--web.console.libraries ./dashboard_libs \
		--storage.tsdb.retention.time 300d
	;;
stop)
	kill -INT $MAINPID
	;;
reload)
	kill -HUP $MAINPID
	;;
*)
	echo "$0: unknown directive '$1'" >&2
	exit 127
	;;
esac
