package walrus

// LogLevel The LogLevel type and associated code are usually
// generated by protobuf generator.  This file allows compilation
// until the walrus protobuf code is fixed.
type LogLevel int32

// Happy lint
const (
	LogLevelPANIC    LogLevel = 0
	LogLevelFATAL    LogLevel = 1
	LogLevelERROR    LogLevel = 2
	LogLevelWARN     LogLevel = 3
	LogLevelINFO     LogLevel = 4
	LogLevelDEBUG    LogLevel = 5
	LogLevelNOCHANGE LogLevel = 6
)

// LogLevelName  Number to string
var LogLevelName = map[int32]string{
	0: "PANIC",
	1: "FATAL",
	2: "ERROR",
	3: "WARN",
	4: "INFO",
	5: "DEBUG",
	6: "NOCHANGE",
}

// LogLevelValue  String to number
var LogLevelValue = map[string]int32{
	"PANIC":    0,
	"FATAL":    1,
	"ERROR":    2,
	"WARN":     3,
	"INFO":     4,
	"DEBUG":    5,
	"NOCHANGE": 6,
}

//String  Log level Number to String
func (x LogLevel) String() string {
	return LogLevelName[int32(x)]
}
