#!/bin/sh

case $# in
2|3)	CA="$1"
	REQ="$2"
	FORCE="$3"
	;;
*)	echo "usage: $0 auth req" >&2
	exit 127
	;;
esac

EXT=sign-ca.$$.ext

trap "rm -f $EXT" EXIT

sed '1,/-----END CERTIFICATE REQUEST-----/d' "$REQ.req" >$EXT

FLAGS=$(sed -n '1,/\[ signing_options \]/d;
	s/^./ -&/; s/=/ /; H;
	${; x; s/\n//g; p; }' $EXT)

openssl x509 -req $FLAGS -extfile $EXT \
	-CA "$CA.crt" -CAkey "$CA.key" -CAcreateserial \
	${FORCE:+-force_pubkey} ${FORCE} -in "$REQ.req" -out "$REQ.crt" &&
echo "Signed '$REQ.crt' with '$CA.key'"
