---
- name: Update Ubuntu to the latest available packages
  hosts:
    - all
  become: yes
  tasks:
    - name: Update apt cache and run a dist-upgrade
      apt:
        update_cache: yes
        upgrade: dist
        dpkg_options: 'force-confold,force-confdef'

    - name: Check if a reboot is required
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no

    - name: restart machine
      when: reboot_required_file.stat.exists == true
      shell: sleep 2 && shutdown -r now "Ansible updates triggered"
      async: 1
      poll: 0
      ignore_errors: yes

    - name: Wait for server to come back
      when: reboot_required_file.stat.exists == true
      become: no
      delegate_to: localhost
      wait_for:
        port: 22
        host: "{{ ansible_default_ipv4.address }}"
        search_regex: "OpenSSH"
        delay: 5
