#!/bin/sh

case "$1" in
default)
	parms=(`ip r ls default | cut -d' ' -f3,5`)
	GWADDR=${parms[0]}
	GWDEV=${parms[1]}
	;;
*)
	GWADDR=$1
	GWDEV=$2
	;;
esac

if [ -z "$GWADDR" -o -z "$GWDEV" ]
then
	echo "usage: $0 gwaddr gwdev" >&2
	exit 127
fi
echo GWADDR $GWADDR GWDEV $GWDEV
if [ "$UID" -ne 0 ]
then
	echo 'sorry, you have to be the superuser' >&2
	exit 126
fi
if grep '^[0-9][0-9]*	from.tunnel$' /etc/iproute2/rt_tables >/dev/null 2>&1
then
	: ok
elif ! grep '^84	' /etc/iproute2/rt_tables >/dev/null 2>&1
then
	echo '84	from.tunnel' >>/etc/iproute2/rt_tables
else
	echo 'conflict in /etc/iproute2/rt_tables' >&2
	exit 125
fi

ip r add default table from.tunnel via ${GWADDR} dev ${GWDEV}
ip ru add fwmark 84 tab from.tunnel priority 1001
ip r flush cache

iptables -t mangle -I PREROUTING -i tun+ -j MARK --set-mark 84 # 'T'
iptables -I FORWARD -i ${GWDEV} -o tun+ -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -I FORWARD -i tun+ -o ${GWDEV} -j ACCEPT
iptables -t nat -A POSTROUTING -o ${GWDEV} -m mark --mark 84 -j MASQUERADE

echo 0 >/proc/sys/net/ipv4/conf/${GWDEV}/rp_filter
echo 1 >/proc/sys/net/ipv4/ip_forward
