package crux

// DO NOT EDIT THIS FILE!! this is code generated by enumerator

import "fmt"

// MonOp is the kind of MonInfo.
type MonOp int

// define the various symbolic constants for type MonOp
const (
	JoinOp        MonOp = 0
	LeaderStartOp MonOp = 1
	LeaderHeartOp MonOp = 2
	LeaderDeltaOp MonOp = 3
	ProbeOp       MonOp = 4
	RebootOp      MonOp = 5
	HeartBeatOp   MonOp = 6
	ExitOp        MonOp = 7
)

// String converts MonOp values into strings.
func (x MonOp) String() string {
	switch x {
	case ExitOp:
		return "ExitOp"
	case HeartBeatOp:
		return "HeartBeatOp"
	case JoinOp:
		return "JoinOp"
	case LeaderDeltaOp:
		return "LeaderDeltaOp"
	case LeaderHeartOp:
		return "LeaderHeartOp"
	case LeaderStartOp:
		return "LeaderStartOp"
	case ProbeOp:
		return "ProbeOp"
	case RebootOp:
		return "RebootOp"
	}
	return fmt.Sprintf("unknown_MonOp_%d", x)
}
