---
# This playbook sets up the production jump node.
- name: Jump node
  hosts:
    - all
  become: yes
  tasks:
    # We expect that a /home volume with a label will be attached at runtime.
    # If not, though, we'll still boot.
    - name: Mount persistent /home partition
      mount:
        path: /home
        src: LABEL=home
        fstype: ext4
        state: present
        opts: nofail

    - name: Install Terraform binary
      unarchive:
        remote_src: yes
        src: "https://releases.hashicorp.com/terraform/0.11.3/terraform_0.11.3_linux_amd64.zip"
        dest: /usr/local/bin
        mode: 0755

    - name: Install Docker Machine
      get_url:
        url: "https://github.com/docker/machine/releases/download/v0.14.0/docker-machine-{{ ansible_system }}-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-machine
        mode: 0755

    - name: Install Ansible repository
      apt_repository:
        repo: "ppa:ansible/ansible"

    - name: Install Ansible
      apt:
        update_cache: yes
        package: ansible

    - name: Install Packer
      unarchive:
        remote_src: yes
        src: "https://releases.hashicorp.com/packer/1.2.3/packer_1.2.3_linux_amd64.zip"
        dest: /usr/local/bin
        mode: 0755

