heat_template_version: 2015-04-30
description: ENM Network External Stack (experimental)

parameters:
  enm_external_network_name:
    type: string

  external_subnet:
    type: string

  external_gateway:
    type: string

  dynamic_external_start:
    type: string

  dynamic_external_end:
    type: string

resources:
  enm_external_network:
    type: OS::Neutron::Net
    properties:
      name: {get_param: enm_external_network_name}

  enm_external_subnet:
    type: OS::Neutron::Subnet
    properties:
      allocation_pools:
      - start: {get_param: dynamic_external_start}
        end: {get_param: dynamic_external_end}
      network_id: {get_resource: enm_external_network}
      cidr: {get_param: external_subnet}
      gateway_ip: {get_param: external_gateway}
