# repair output of yacc and nex so that it passes vet and lint
nex -p parse -o crap lexer.nex
awk '/break OUTER0/ { delc = 1 }
/continue/ { if(delc == 1) printf("//")}
/type Lexer / { printf("// Lexer is autogenerated\n")}
/func NewLexer[(]/ { printf("// NewLexer is autogenerated\n")}
{print $0}' < crap > lexer.nn.go; rm crap
go tool yacc -p parse -o crap parse.y
awk '/^const/ { printf("// %s is a token\n", $2)}
{print $0}' < crap | sed 's/parseEofCode/parseEOFCode/g;s/parsercvr/p/g' > parse.go; rm crap
